apiVersion: v1
kind: Service
metadata:
  name: api-pipeline
  namespace: default
spec:
  selector:
    app: api-pipeline
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
