name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.3"

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/api-pipeline:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/api-pipeline:${{ github.sha }}

      - name: Update image tag in deployment
        if: github.ref == 'refs/heads/main'
        run: |
          sed -i "s|image: danielmoisa/api-pipeline:.*|image: danielmoisa/api-pipeline:${{ github.sha }}|g" k8s/base/deployment.yaml
          git config user.email "ci@github.com"
          git config user.name "GitHub Actions"
          git add k8s/base/deployment.yaml
          git commit -m "ci: update image to ${{ github.sha }}"
          git push
